POST http://localhost:8080/exercise
Content-type: application/json

{
    "startTime": "2022-01-01 11:50",
    "durationInSeconds": 60,
    "activityType": "running"
}

###

GET http://localhost:8080/exercise

###

GET http://localhost:8080/exercise/638f0496e8fb58228c5e6968